services:
  - type: cron
    name: buscar-turno
    schedule: "*/30 * * * *"
    runtime: python
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
