name: Buscar Turno Bot

on:
  schedule:
    - cron: "*/30 * * * *"  # Ejecuta cada 30 minutos
  workflow_dispatch:       # Permite ejecución manual

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py
