name: Buscar Turno Bot

on:
  schedule:
    - cron: "*/30 * * * *"    # Ejecutar cada 30 minutos
  workflow_dispatch:           # Permite ejecución manual desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        run: python main.py
